/*
 * Structure
 */

DROP TABLE product IF EXISTS;

CREATE TABLE product
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    name          VARCHAR(100)                                           NOT NULL,
    current_price NUMERIC(10, 2)                                         NOT NULL,
    last_update   DATETIME DEFAULT NULL,
    PRIMARY KEY (id)
);
