/*
 * Engine: H2
 * Version: 0.0.1
 * Description: Initial database structure and data.
 */

/*
 * Structure
 */

CREATE TABLE product
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    name          VARCHAR(100)                                           NOT NULL,
    current_price NUMERIC(10, 2)                                         NOT NULL,
    last_update   DATETIME                                               NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_product_name UNIQUE (name)
);

/*
 * Data
 */

INSERT INTO product (name, current_price, last_update) VALUES ('Apple EarPods', '16.44', NOW());
INSERT INTO product (name, current_price, last_update) VALUES ('Apple Macbook Air (2019)', '1005.88', NOW());
INSERT INTO product (name, current_price, last_update) VALUES ('BenQ TK800M 4K DLP Beamer', '1110', NOW());
INSERT INTO product (name, current_price, last_update) VALUES ('LG PH550G HD Mini Beamer', '369', NOW());
INSERT INTO product (name, current_price, last_update) VALUES ('Canon EOS 2000D', '375.99', NOW());